### ISSUE TITLE
Set dependencies

### ISSUE THREAD

**Issue by stefangeorg** [bdemchak/py4cytoscape#10]
https://github.com/bdemchak/py4cytoscape/blob/d81f93af4fbc96ac055ec723248917b848ac1ef9/py4cytoscape/style_dependencies.py#L121

Line 121:
 res = commands.commands_post(f'vizmap apply styles="{style_name}"')

Is missing base_url=base_url

**Comment by bdemchak** [comment]
Thanks ... I have eyeballed all other sites where this could have been missing. This seems to be the only one. Did this actually bite you, or did this come out of a code analysis you were doing? Either way, I'm happy you're here. Feel free to raise more issues or discuss more.

**Comment by stefangeorg** [comment]
Hi, I was helping someone today, and it did bite us. We added a try/except around the call to the set_node_map I think. It was working so seems the line 121 wasn't required for it to work, so catching the exception let us continue, but figured I'd raise it here so it could be fixed for anyone else who might struggle to debug it when running on a non standard port.

**Comment by bdemchak** [comment]
Indeed … good catch. It’s fixed now.

 

This py4cytoscape project is for real, and real projects thrive on the quality of contributions, especially suggestions. Please feel free to open more issues as they appear, including ease-of-use and missing functionality issues. 

 

Thanks!
